version: "3"
services:
  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile_api
    environment:
      REDIS_IP: redis
      LOG_LEVEL: DEBUG
      KAGGLE_USERNAME: username
      KAGGLE_KEY: key
      KAGGLE_OWNER: kelvinkelue
      KAGGLE_DATASET: credit-card-fraud-prediction
      KAGGLE_FILENAME: fraud test.csv
      FALLBACK_DATASET_PATH: /data/fraud_test.csv
    ports:
      - 5173:5173
    volumes:
      - ./data-fallback:/data
    depends_on:
      - redis
    command: python api.py
  worker:
    build:
      context: ./
      dockerfile: Dockerfile_worker
    environment:
      REDIS_IP: redis
      LOG_LEVEL: DEBUG
    depends_on:
      - redis
    command: python worker.py
