FROM python:3.10-slim

WORKDIR /app
COPY test/requirements_test.txt ./
RUN pip install -r requirements_test.txt

COPY src/api.py src/services.py src/worker.py test/test_api.py test/test_services.py test/test_worker.py ./
