FROM python:3.10-slim

WORKDIR /app
COPY src/requirements_worker.txt ./
RUN pip install -r requirements_worker.txt

COPY src/services.py src/worker.py src/ml/binaryclassifierstate.pt src/ml/input_vectorization.py src/ml/meanandstd.txt src/ml/ml_model.py src/ml/merchants.txt src/ml/categories.txt src/ml/jobs.txt ./
