version: "3"
services:
  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile_api
    environment:
      REDIS_IP: redis
      LOG_LEVEL: DEBUG
    ports:
      - 5173:5173
    depends_on:
      - redis
    command: python api.py
  worker:
    build:
      context: ./
      dockerfile: Dockerfile_worker
    environment:
      REDIS_IP: redis
      LOG_LEVEL: DEBUG
    depends_on:
      - redis
    command: python worker.py
